CREATE TABLE Workout(
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    'Date' VARCHAR(50) NOT NULL,
     WorkoutType VARCHAR(100) NOT NULL,
    'Distance'VARCHAR(100) NOT NULL,
    'Remarks' VARCHAR(300) NOT NULL
)